services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 12

  auth-service:
    build: ./auth-service
    image: taskmaster/auth-service:latest
    ports: ["8081:8080"]
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  task-service:
    build: ./task-service
    image: taskmaster/task-service:latest
    ports: ["8082:8080"]
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  feed-service:
    build: ./feed-service
    image: taskmaster/feed-service:latest
    ports: ["8083:8080"]
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  default:
    name: taskmaster-net
