services:
  auth-service:
    build: ./auth-service
    image: taskmaster/auth-service:latest
    ports: ["8081:8080"]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 6

  task-service:
    build: ./task-service
    image: taskmaster/task-service:latest
    ports: ["8082:8080"]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 6

  feed-service:
    build: ./feed-service
    image: taskmaster/feed-service:latest
    ports: ["8083:8080"]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 6

networks:
  default:
    name: taskmaster-net
